[graph]
all-features = true
targets = [
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-unknown-linux-musl" },
]

[advisories]
version = 2
yanked = "deny"
ignore = []

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "Unicode-3.0",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
